# DVA_Lab 01_NumPy Basics Roll:no:225229106


# 1)Add the np import directive to the numpy package

In [9]:
import numpy as np

# 2)Publish the configuration and the numpy version

In [2]:
print("NumPy Version : ",np.__version__)
print(np.show_config())


NumPy Version :  1.14.0
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Program Files (x86)/Microsoft Visual Studio/Shared/Anaconda3_64\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Program Files (x86)/Microsoft Visual Studio/Shared/Anaconda3_64\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Program Files (x86)/Microsoft Visual Studio/Shared/Anaconda3_64\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_a

# 3) Make a null vector of 10 bytes.

In [8]:
import numpy as np
x = np.zeros(10)
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 4)How to determine an array's memory size


In [11]:
# import library
import numpy as np

# create numpy 1d-array
x = np.array([100, 20, 34])

print("Memory size of a NumPy array:",
x.itemsize)


Memory size of a NumPy array: 4


## 5)How can I see the command-line documentation for the numpy add function? Make a 10-dimensional null vector with the fifth valueset to 1 instead.


In [12]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [13]:
arr2 = np.zeros(10)
arr2[4] = 1
print(arr2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 6)Make a vector containing values in the range of 50 to 99.

In [15]:
import numpy as np
x = np.arange(50,100)
print(x)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


# 7) Transform a vector (first element becomes last)


In [17]:
import numpy as np
x = np.arange(1,10)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)


Original array:
[1 2 3 4 5 6 7 8 9]
Reverse array:
[9 8 7 6 5 4 3 2 1]


# 8) Make a 4x4 matrix with values from 0 to 16 in it.

In [19]:
import numpy as np
#creating matrix from string
A = np.matrix('0 1 2 3;4 5 6 7;8 9 10 11;12 13 14 15')
print("Array created using string is :\n", A)

Array created using string is :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# 9)Search for non-zero element indices in the range [1,2,0,0,4,0].

In [24]:
# Python program explaining
# nonzero() function
import numpy as geek
arr = geek.array([1,2,0,0,4,0])
print ("Input array : \n", arr)
out_tpl = geek.nonzero(arr)
print ("Indices of non zero elements : ", out_tpl)
# Python program for getting
# The corresponding non-zero values:
out_arr = arr[geek.nonzero(arr)]

print ("Output array of non-zero number: ", out_arr)


Input array : 
 [1 2 0 0 4 0]
Indices of non zero elements :  (array([0, 1, 4], dtype=int64),)
Output array of non-zero number:  [1 2 4]


# 10)Construct a 4 by 4 identity matrix.

In [25]:
import numpy as np

matrix_int = np.identity(4, dtype = int)
print(matrix_int)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# 11)Build a 4x4x4 array with arbitrary values.

In [26]:
import numpy as np
x = np.random.random((4, 4, 4))
print(x)

[[[0.77046314 0.66306496 0.95098453 0.66470326]
  [0.86188943 0.94395541 0.817324   0.98961553]
  [0.65341575 0.81758581 0.47504604 0.83089614]
  [0.35775782 0.65005826 0.71218467 0.16080596]]

 [[0.62277189 0.34361151 0.48790908 0.35394018]
  [0.17797828 0.44955782 0.40605887 0.48714043]
  [0.98879601 0.89429223 0.94529386 0.25247115]
  [0.6694323  0.53530049 0.7614917  0.2552295 ]]

 [[0.9796827  0.52477475 0.63107423 0.20888793]
  [0.15432531 0.43686297 0.01528331 0.78958835]
  [0.2688331  0.3667379  0.24854772 0.56765475]
  [0.23005344 0.32707397 0.62183062 0.48910341]]

 [[0.45172596 0.30126179 0.03282796 0.53956377]
  [0.91912483 0.38867951 0.35052461 0.99585936]
  [0.07486607 0.66956227 0.44271457 0.19979143]
  [0.64875457 0.47698957 0.28310474 0.89484205]]]


# 12) Find the minimum and highest values in an 11x11 array you've created with random values.


In [40]:
import numpy as np
x = np.random.random((11,11))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.84425063 0.98151409 0.7495053  0.65063226 0.3848018  0.64377738
  0.01206373 0.07478914 0.58783048 0.65098218 0.45610606]
 [0.16128103 0.4298479  0.62279025 0.55407466 0.74611169 0.9202379
  0.70621628 0.1942074  0.12826283 0.7536915  0.76671917]
 [0.67954376 0.57907842 0.91619104 0.4691941  0.23205943 0.48947285
  0.6325097  0.75284401 0.72114983 0.48015239 0.35734269]
 [0.12449569 0.71256159 0.52075003 0.13148921 0.79625017 0.47802378
  0.56575856 0.76435147 0.32001264 0.26540918 0.11864103]
 [0.85769142 0.14981632 0.28801105 0.51207148 0.48653692 0.1603767
  0.33888542 0.9345251  0.62942884 0.52906812 0.78384771]
 [0.06061576 0.55968927 0.00906152 0.71787764 0.16367968 0.06932282
  0.81109036 0.17439521 0.00785682 0.76446936 0.56428584]
 [0.26600543 0.18309728 0.21604439 0.94311819 0.87704927 0.02918613
  0.50930097 0.96594305 0.17499833 0.65843538 0.34107293]
 [0.30563795 0.63636147 0.56500257 0.611317   0.509725   0.46408601
  0.77784675 0.24030006 0.12862724 0

# 13)Obtain the mean value by creating a random vector of size 15.

In [44]:
import numpy as np
import statistics
x = np.random.random(15)
y = statistics.mean(data1)
print("Original array:")
print(x)
print("The mean value for the vector:",y)


Original array:
[0.54980693 0.36834158 0.32493649 0.93530521 0.36118776 0.44055814
 0.17296668 0.17077447 0.54752305 0.48663735 0.14338025 0.62506413
 0.00497057 0.1429703  0.93848012]
The mean value for the vector: 4.428571428571429


# 14)Make a 3D array with 1 inside and 0 outside. A 4x4 matrix with the numbers 4,3,2,1 should be created directly below the diagonal.

In [2]:
import numpy as np
x = np.ones((5,5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
1 on the border and 0 inside in the array
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 

# 15) Make an 8x8 matrix and place a checkerboard pattern inside of it.


In [46]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 16) What is the (x,y,z) index of the 80th member in an array of shape (8,7,6)?

In [53]:
print(np.unravel_index(80,(8,7,6)))

(1, 6, 2)


# 17)Add a 3x5 matrix to a 5x2 matrix (real matrix  product)


In [47]:
import numpy as np
x = np.random.random((3,5))
print("First array:")
print(x)
y = np.random.random((5,2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)


First array:
[[0.88105503 0.39027046 0.77386378 0.16652849 0.05849301]
 [0.67528798 0.72018434 0.34585754 0.11854492 0.83049978]
 [0.54443109 0.51535129 0.04004568 0.08173583 0.9834245 ]]
Second array:
[[0.70742172 0.32270606]
 [0.69371596 0.52277615]
 [0.95073193 0.73131427]
 [0.96308605 0.31764034]
 [0.59483524 0.63158283]]
Dot product of two arrays:
[[1.82492629 1.14412287]
 [1.91431405 1.40952932]
 [1.4444167  1.12146719]]


# 18)In a 1D array, negate any element that falls between 8 and 5.


In [54]:
import numpy as np
x = np.arange(1,11)
print(x)



[ 1  2  3  4  5  6  7  8  9 10]


# 19)# How can two arrays with similar values be found?How can I get today's, yesterday's, and tomorrow's dates?


In [55]:
# Python program to find yesterday,
# today and tomorrow


# Import datetime and timedelta
# class from datetime module
from datetime import datetime, timedelta


# Get today's date
presentday = datetime.now() # or presentday = datetime.today()

# Get Yesterday
yesterday = presentday - timedelta(1)

# Get Tomorrow
tomorrow = presentday + timedelta(1)


# strftime() is to format date according to
# the need by converting them to string
print("Yesterday = ", yesterday.strftime('%d-%m-%Y'))
print("Today = ", presentday.strftime('%d-%m-%Y'))
print("Tomorrow = ", tomorrow.strftime('%d-%m-%Y'))


Yesterday =  20-12-2022
Today =  21-12-2022
Tomorrow =  22-12-2022


# 20)Identify the integers in a positive random array of numbers.


In [15]:
np.random.randint(5,size=10)

array([0, 4, 3, 2, 3, 2, 1, 1, 2, 3])

# 21)Make a 6x6 matrix with a row range of 0 to 5.


In [56]:
import numpy as np
x = np.zeros((6,6))
print("Original array:")
print(x)
print("Row values ranging from 0 to 4.")
x += np.arange(6)
print(x)


Original array:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]


# 22)Check to see if the two random arrays, X and Y, are equal.

In [12]:
def areEqual(arr1, arr2, N, M):
 
    # If lengths of array are not
    # equal means array are not equal
    if (N != M):
        return False
 
    # Sort both arrays
    arr1.sort()
    arr2.sort()
 
    # Linearly compare elements
    for i in range(0, N):
        if (arr1[i] != arr2[i]):
            return False
 
    # If all elements were same.
    return True

if __name__ == "__main__":
    arr1 = [3, 5, 2, 5, 2]
    arr2 = [2, 3, 5, 5, 2]
    n = len(arr1)
    m = len(arr2)
 
    if (areEqual(arr1, arr2, n, m)):
        print("Yes")
    else:
        print("No")

Yes


# 23) Make a random vector of 15 bytes in size andchange the minimum value to -1.


In [17]:
import numpy as np
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmin()] = -1
print("Minimum value replaced by -1:")
print(x)



Original array:
[0.61843729 0.71246861 0.99554424 0.1377199  0.71170276 0.91972465
 0.55134166 0.54565866 0.55573436 0.40390278 0.13918138 0.39638546
 0.33982737 0.35040252 0.77107492]
Minimum value replaced by -1:
[ 0.61843729  0.71246861  0.99554424 -1.          0.71170276  0.91972465
  0.55134166  0.54565866  0.55573436  0.40390278  0.13918138  0.39638546
  0.33982737  0.35040252  0.77107492]


# 24) Print the smallest and largest value that each numpy scalar type can represent.

In [22]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


# 25.  How can I print an array's entire value set?

In [23]:
import numpy as np
arr = np.arange(1001)
print(arr)


[   0    1    2 ...  998  999 1000]


# 26.  How can I instantly convert a 32-bit float array to a 32-bit integer array?


In [25]:
# conversion from float to int

num = 8.5

# printing data type of 'num'
print('type:',
	type(num).__name__)

# conversion to int
num = int(num)

# printing data type of 'num'
print('converted value:', num,
	', type:', type(num).__name__)


type: float
converted value: 8 , type: int


# 27.  Subtract the matrix's average for each row.


In [27]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(1,3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.86552955 0.16581045 0.25358922]]

Subtract the mean of each row of the said matrix:

[[ 0.43721981 -0.26249929 -0.17472052]]


# 28.  How can an array be sorted by the nth column?



In [33]:
import numpy as np
inputArray = np.random.randint(0,100,(4,4))
print("The input random array is:")
print(inputArray)
n = 2
print("Sorting the input array by the",n,"column:")
print(inputArray[inputArray[:,n].argsort()])


The input random array is:
[[32 56 51 64]
 [81 14 67 66]
 [18 26 21 37]
 [47 88 27 95]]
Sorting the input array by the 2 column:
[[18 26 21 37]
 [47 88 27 95]
 [32 56 51 64]
 [81 14 67 66]]


# 29.  How can the sum of two arrays with the shapes (2,4) and (4,2) be calculated?



In [30]:
A = np.ones((2,4))
B = 2+np.zeros((4,2))
c=A * B[:,:,None]
print(c)



[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


# 30.  How can two columns in an array be switched?

In [32]:
import numpy as np
my_array = np.arange(12).reshape(4, 3)
print("Original array:")
print(my_array)
my_array[:, [2, 0]] = my_array[:, [0, 2]]
print("After swapping arrays the last column and first column:")
print(my_array)


Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping arrays the last column and first column:
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]
