Name:Pavithra S
Roll no:225229125

# Red Wine Quality Data Analysis using Numpy Part-I

# Import modules for numpy

In [1]:
import numpy as np

In [4]:
wines=np.genfromtxt("winequality-red.csv",delimiter=";",skip_header=1)


# what is its shape

In [5]:
wines.shape

(1599, 12)

# How Many Rows here?

In [6]:
wines.shape[0]

1599

# How Many Columns here?

In [7]:
wines.shape[1]

12

# How Many dimension?

In [8]:
wines.ndim

2

# What  is the Type of wines?

In [9]:
type(wines)

numpy.ndarray

# What is the data type of wines data?

In [10]:
wines.dtype

dtype('float64')

# show top 5 rows

In [13]:
#wines[:5,:]

# What is the value at 3 row 4th column of wine data

In [14]:
wines[2,3]

2.3

# Select first 3 items in 4th column

In [15]:
wines[:3,3]

array([1.9, 2.6, 2.3])

# Show 1st Column

In [16]:
wines[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

# show 2nd row

In [18]:
wines[1,:]

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,  5.    ])

# Select items from rows 1 to3 and 5 th column

In [19]:
wines[1:4,4]

array([0.098, 0.092, 0.075])

# Select entire Array

In [20]:
wines[:,:]

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

# Change 1st value in wines to 100

In [21]:
wines[0,0]

7.4

In [22]:
wines[0,0]=100
wines[0,0]

100.0

In [23]:
#change it back to 7.4 and print

In [24]:
wines[0,0]=7.4

In [25]:
print(wines[0,0])

7.4


# 1-Dimensional Numpy Array

# Select 4th row all column values

In [27]:
third_wines=wines[3,:]

# display the value

In [29]:
third_wines

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

# show 2nd value

In [31]:
third_wines[1]

0.28

# Convert wine data to integer values and show it

In [32]:
wines.astype(int)

array([[ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       ...,
       [ 6,  0,  0, ...,  0, 11,  6],
       [ 5,  0,  0, ...,  0, 10,  5],
       [ 6,  0,  0, ...,  0, 11,  6]])

# Vectorization Operation

# Increase  wine quality score By 10

In [33]:
wines[:,11]

array([5., 5., 5., ..., 6., 5., 6.])

# Increase By 10

In [34]:
wines[:,11]+=10

# Display update score

In [35]:
wines[:,10]

array([ 9.4,  9.8,  9.8, ..., 11. , 10.2, 11. ])

# Mutliply alcohol of all wines data by 3 times

In [37]:
wines[:,10]*=3

# Show update alcohol column

In [38]:
wines[:,10]

array([28.2, 29.4, 29.4, ..., 33. , 30.6, 33. ])

# Add Quality column by itself

In [40]:
wines[:,11]+wines[:,11]

array([30., 30., 30., ..., 32., 30., 32.])

# Multiply alcohol and quantity .It will Perform element wise multiplication

In [43]:
wines[:,10]*wines[:,11]

array([423., 441., 441., ..., 528., 459., 528.])

# Broadcasting

# Add every row of wines data with a random array of values


In [44]:
rand_array=np.random.rand(12)

# Show rand_array

In [45]:
rand_array

array([0.79294536, 0.58532392, 0.2127691 , 0.05354873, 0.2275005 ,
       0.59330834, 0.53676124, 0.73236886, 0.65993543, 0.47644021,
       0.51051626, 0.22993429])

# Add wines and rand_array

In [46]:
wines+rand_array

array([[ 8.19294536,  1.28532392,  0.2127691 , ...,  1.03644021,
        28.71051626, 15.22993429],
       [ 8.59294536,  1.46532392,  0.2127691 , ...,  1.15644021,
        29.91051626, 15.22993429],
       [ 8.59294536,  1.34532392,  0.2527691 , ...,  1.12644021,
        29.91051626, 15.22993429],
       ...,
       [ 7.09294536,  1.09532392,  0.3427691 , ...,  1.22644021,
        33.51051626, 16.22993429],
       [ 6.69294536,  1.23032392,  0.3327691 , ...,  1.18644021,
        31.11051626, 15.22993429],
       [ 6.79294536,  0.89532392,  0.6827691 , ...,  1.13644021,
        33.51051626, 16.22993429]])